### ISSUE TITLE
Complexity Budget management

### ISSUE THREAD

**Issue by ericjpeters** [clintmasden/monday.client.v2#7]
While using this library, I was having problems exceeding my complexity budget pretty regularly.  I have started a fork with my ideas on how to extend this project so that the rate-limits can be better managed by the consuming code.

As it stands right now, the code is only partially thought through, and only addresses the minimal needs I have at this moment.  But I'm happy to expand upon the ideas if you think a pull request would be worth while.   If you have a minute, could you take a peek at https://github.com/ericjpeters/monday.client.v2/tree/queryComplexityManagement and let me know if this would be something you would like a pull request for?

I'll be happy to continue fleshing out our collaborative ideas if you would like to include it in your code base.

Thanks!

**Comment by clintmasden** [comment]
This is expected which is why the `CustomQueryOrMutation()` method was mandatory. 

I also hit the complexity limit after 3 uses of the `GetItems()` method or any custom method that returned / included a ton of properties. (_`GetItems()` was a proof of concept from the beginning and for sure can be improved._)  

Your branch/implementation looks good and should be applied to some of the bigger queries / mutations. I believe some type of configuration/parameters should be used for any standard method, yet since every single user can create their own returns from `CustomQueryOrMutation()` it should be a simple minded as possible. 

I'll end with I have not needed to leverage Monday's API in quite a while yet since this repo is being leveraged by quite a few I'm willing to keep any improvements up to date and push the nuget after any code review / pull request.
